// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/BaseResponseProto.proto

package com.liang.pigeonim.common.protocol;

public final class PigeonIMResponseProto {
  private PigeonIMResponseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PigeonIMResProcotolOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.PigeonIMResProcotol)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string resMsg = 1;</code>
     * @return The resMsg.
     */
    java.lang.String getResMsg();
    /**
     * <code>string resMsg = 1;</code>
     * @return The bytes for resMsg.
     */
    com.google.protobuf.ByteString
        getResMsgBytes();

    /**
     * <code>int64 responseId = 2;</code>
     * @return The responseId.
     */
    long getResponseId();

    /**
     * <code>int32 type = 3;</code>
     * @return The type.
     */
    int getType();
  }
  /**
   * Protobuf type {@code protocol.PigeonIMResProcotol}
   */
  public static final class PigeonIMResProcotol extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.PigeonIMResProcotol)
      PigeonIMResProcotolOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PigeonIMResProcotol.newBuilder() to construct.
    private PigeonIMResProcotol(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PigeonIMResProcotol() {
      resMsg_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PigeonIMResProcotol();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PigeonIMResProcotol(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              resMsg_ = s;
              break;
            }
            case 16: {

              responseId_ = input.readInt64();
              break;
            }
            case 24: {

              type_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.liang.pigeonim.common.protocol.PigeonIMResponseProto.internal_static_protocol_PigeonIMResProcotol_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.liang.pigeonim.common.protocol.PigeonIMResponseProto.internal_static_protocol_PigeonIMResProcotol_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.liang.pigeonim.common.protocol.PigeonIMResponseProto.PigeonIMResProcotol.class, com.liang.pigeonim.common.protocol.PigeonIMResponseProto.PigeonIMResProcotol.Builder.class);
    }

    public static final int RESMSG_FIELD_NUMBER = 1;
    private volatile java.lang.Object resMsg_;
    /**
     * <code>string resMsg = 1;</code>
     * @return The resMsg.
     */
    @java.lang.Override
    public java.lang.String getResMsg() {
      java.lang.Object ref = resMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resMsg_ = s;
        return s;
      }
    }
    /**
     * <code>string resMsg = 1;</code>
     * @return The bytes for resMsg.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getResMsgBytes() {
      java.lang.Object ref = resMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESPONSEID_FIELD_NUMBER = 2;
    private long responseId_;
    /**
     * <code>int64 responseId = 2;</code>
     * @return The responseId.
     */
    @java.lang.Override
    public long getResponseId() {
      return responseId_;
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private int type_;
    /**
     * <code>int32 type = 3;</code>
     * @return The type.
     */
    @java.lang.Override
    public int getType() {
      return type_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getResMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, resMsg_);
      }
      if (responseId_ != 0L) {
        output.writeInt64(2, responseId_);
      }
      if (type_ != 0) {
        output.writeInt32(3, type_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getResMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, resMsg_);
      }
      if (responseId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, responseId_);
      }
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, type_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.liang.pigeonim.common.protocol.PigeonIMResponseProto.PigeonIMResProcotol)) {
        return super.equals(obj);
      }
      com.liang.pigeonim.common.protocol.PigeonIMResponseProto.PigeonIMResProcotol other = (com.liang.pigeonim.common.protocol.PigeonIMResponseProto.PigeonIMResProcotol) obj;

      if (!getResMsg()
          .equals(other.getResMsg())) return false;
      if (getResponseId()
          != other.getResponseId()) return false;
      if (getType()
          != other.getType()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESMSG_FIELD_NUMBER;
      hash = (53 * hash) + getResMsg().hashCode();
      hash = (37 * hash) + RESPONSEID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getResponseId());
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.liang.pigeonim.common.protocol.PigeonIMResponseProto.PigeonIMResProcotol parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.liang.pigeonim.common.protocol.PigeonIMResponseProto.PigeonIMResProcotol parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.liang.pigeonim.common.protocol.PigeonIMResponseProto.PigeonIMResProcotol parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.liang.pigeonim.common.protocol.PigeonIMResponseProto.PigeonIMResProcotol parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.liang.pigeonim.common.protocol.PigeonIMResponseProto.PigeonIMResProcotol parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.liang.pigeonim.common.protocol.PigeonIMResponseProto.PigeonIMResProcotol parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.liang.pigeonim.common.protocol.PigeonIMResponseProto.PigeonIMResProcotol parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.liang.pigeonim.common.protocol.PigeonIMResponseProto.PigeonIMResProcotol parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.liang.pigeonim.common.protocol.PigeonIMResponseProto.PigeonIMResProcotol parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.liang.pigeonim.common.protocol.PigeonIMResponseProto.PigeonIMResProcotol parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.liang.pigeonim.common.protocol.PigeonIMResponseProto.PigeonIMResProcotol parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.liang.pigeonim.common.protocol.PigeonIMResponseProto.PigeonIMResProcotol parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.liang.pigeonim.common.protocol.PigeonIMResponseProto.PigeonIMResProcotol prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.PigeonIMResProcotol}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.PigeonIMResProcotol)
        com.liang.pigeonim.common.protocol.PigeonIMResponseProto.PigeonIMResProcotolOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.liang.pigeonim.common.protocol.PigeonIMResponseProto.internal_static_protocol_PigeonIMResProcotol_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.liang.pigeonim.common.protocol.PigeonIMResponseProto.internal_static_protocol_PigeonIMResProcotol_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.liang.pigeonim.common.protocol.PigeonIMResponseProto.PigeonIMResProcotol.class, com.liang.pigeonim.common.protocol.PigeonIMResponseProto.PigeonIMResProcotol.Builder.class);
      }

      // Construct using com.liang.pigeonim.common.protocol.PigeonIMResponseProto.PigeonIMResProcotol.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        resMsg_ = "";

        responseId_ = 0L;

        type_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.liang.pigeonim.common.protocol.PigeonIMResponseProto.internal_static_protocol_PigeonIMResProcotol_descriptor;
      }

      @java.lang.Override
      public com.liang.pigeonim.common.protocol.PigeonIMResponseProto.PigeonIMResProcotol getDefaultInstanceForType() {
        return com.liang.pigeonim.common.protocol.PigeonIMResponseProto.PigeonIMResProcotol.getDefaultInstance();
      }

      @java.lang.Override
      public com.liang.pigeonim.common.protocol.PigeonIMResponseProto.PigeonIMResProcotol build() {
        com.liang.pigeonim.common.protocol.PigeonIMResponseProto.PigeonIMResProcotol result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.liang.pigeonim.common.protocol.PigeonIMResponseProto.PigeonIMResProcotol buildPartial() {
        com.liang.pigeonim.common.protocol.PigeonIMResponseProto.PigeonIMResProcotol result = new com.liang.pigeonim.common.protocol.PigeonIMResponseProto.PigeonIMResProcotol(this);
        result.resMsg_ = resMsg_;
        result.responseId_ = responseId_;
        result.type_ = type_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.liang.pigeonim.common.protocol.PigeonIMResponseProto.PigeonIMResProcotol) {
          return mergeFrom((com.liang.pigeonim.common.protocol.PigeonIMResponseProto.PigeonIMResProcotol)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.liang.pigeonim.common.protocol.PigeonIMResponseProto.PigeonIMResProcotol other) {
        if (other == com.liang.pigeonim.common.protocol.PigeonIMResponseProto.PigeonIMResProcotol.getDefaultInstance()) return this;
        if (!other.getResMsg().isEmpty()) {
          resMsg_ = other.resMsg_;
          onChanged();
        }
        if (other.getResponseId() != 0L) {
          setResponseId(other.getResponseId());
        }
        if (other.getType() != 0) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.liang.pigeonim.common.protocol.PigeonIMResponseProto.PigeonIMResProcotol parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.liang.pigeonim.common.protocol.PigeonIMResponseProto.PigeonIMResProcotol) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object resMsg_ = "";
      /**
       * <code>string resMsg = 1;</code>
       * @return The resMsg.
       */
      public java.lang.String getResMsg() {
        java.lang.Object ref = resMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          resMsg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string resMsg = 1;</code>
       * @return The bytes for resMsg.
       */
      public com.google.protobuf.ByteString
          getResMsgBytes() {
        java.lang.Object ref = resMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          resMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string resMsg = 1;</code>
       * @param value The resMsg to set.
       * @return This builder for chaining.
       */
      public Builder setResMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        resMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string resMsg = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearResMsg() {
        
        resMsg_ = getDefaultInstance().getResMsg();
        onChanged();
        return this;
      }
      /**
       * <code>string resMsg = 1;</code>
       * @param value The bytes for resMsg to set.
       * @return This builder for chaining.
       */
      public Builder setResMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        resMsg_ = value;
        onChanged();
        return this;
      }

      private long responseId_ ;
      /**
       * <code>int64 responseId = 2;</code>
       * @return The responseId.
       */
      @java.lang.Override
      public long getResponseId() {
        return responseId_;
      }
      /**
       * <code>int64 responseId = 2;</code>
       * @param value The responseId to set.
       * @return This builder for chaining.
       */
      public Builder setResponseId(long value) {
        
        responseId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 responseId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearResponseId() {
        
        responseId_ = 0L;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <code>int32 type = 3;</code>
       * @return The type.
       */
      @java.lang.Override
      public int getType() {
        return type_;
      }
      /**
       * <code>int32 type = 3;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 type = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.PigeonIMResProcotol)
    }

    // @@protoc_insertion_point(class_scope:protocol.PigeonIMResProcotol)
    private static final com.liang.pigeonim.common.protocol.PigeonIMResponseProto.PigeonIMResProcotol DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.liang.pigeonim.common.protocol.PigeonIMResponseProto.PigeonIMResProcotol();
    }

    public static com.liang.pigeonim.common.protocol.PigeonIMResponseProto.PigeonIMResProcotol getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PigeonIMResProcotol>
        PARSER = new com.google.protobuf.AbstractParser<PigeonIMResProcotol>() {
      @java.lang.Override
      public PigeonIMResProcotol parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PigeonIMResProcotol(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PigeonIMResProcotol> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PigeonIMResProcotol> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.liang.pigeonim.common.protocol.PigeonIMResponseProto.PigeonIMResProcotol getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_PigeonIMResProcotol_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_PigeonIMResProcotol_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n protocol/BaseResponseProto.proto\022\010prot" +
      "ocol\"G\n\023PigeonIMResProcotol\022\016\n\006resMsg\030\001 " +
      "\001(\t\022\022\n\nresponseId\030\002 \001(\003\022\014\n\004type\030\003 \001(\005B;\n" +
      "\"com.liang.pigeonim.common.protocolB\025Pig" +
      "eonIMResponseProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protocol_PigeonIMResProcotol_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_PigeonIMResProcotol_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_PigeonIMResProcotol_descriptor,
        new java.lang.String[] { "ResMsg", "ResponseId", "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
