server:
  port: 8082

spring:
  application:
    name: pigeonim-client
  cloud:
    nacos:
      discovery:
        server-addr: @nacos.addr@
      config:
        username: @nacos.username@
        password: @nacos.password@
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      indent_output: true
      fail_on_empty_beans: true
    defaultPropertyInclusion: ALWAYS
    deserialization:
      fail_on_unknown_properties: false
    parser:
      allow_unquoted_control_chars: true
      allow_single_quotes: true
  mvc:
    throw-exception-if-no-handler-found: true
    resources:
      add-mappings: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/pigeon_im?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&tinyInt1isBit=false
    username: xxxxxxx
    password: xxxxxxx
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include: '*'

pigeonim:
  user:
    id: xxxxxxx
    username: liangzhenlin
  route:
    url: http://127.0.0.1:8083/
  heartbeat:
    time: 60
  reconnect:
    count: 3
