server:
  port: 8082

spring:
  application:
    name: pigeonim-client
  cloud:
    nacos:
      discovery:
        server-addr: @nacos.addr@
      config:
        username: @nacos.username@
        password: @nacos.password@
  jackson:
    #\u65E5\u671F\u683C\u5F0F\u5316
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      #\u683C\u5F0F\u5316\u8F93\u51FA
      indent_output: true
      #\u5FFD\u7565\u65E0\u6CD5\u8F6C\u6362\u7684\u5BF9\u8C61
      fail_on_empty_beans: true
    #\u8BBE\u7F6E\u7A7A\u5982\u4F55\u5E8F\u5217\u5316
    defaultPropertyInclusion: ALWAYS
    deserialization:
      #\u5141\u8BB8\u5BF9\u8C61\u5FFD\u7565json\u4E2D\u4E0D\u5B58\u5728\u7684\u5C5E\u6027
      fail_on_unknown_properties: false
    parser:
      #\u5141\u8BB8\u51FA\u73B0\u7279\u6B8A\u5B57\u7B26\u548C\u8F6C\u4E49\u7B26
      allow_unquoted_control_chars: true
      #\u5141\u8BB8\u51FA\u73B0\u5355\u5F15\u53F7
      allow_single_quotes: true
  mvc:
    throw-exception-if-no-handler-found: true
    resources:
      add-mappings: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/pigeon_im?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&tinyInt1isBit=false
    username: root
    password: LZLlzl12345
    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      # \u914D\u7F6E\u521D\u59CB\u5316\u5927\u5C0F\u3001\u6700\u5C0F\u3001\u6700\u5927 (\u901A\u5E38\u6765\u8BF4\uFF0C\u53EA\u9700\u8981\u4FEE\u6539initialSize\u3001minIdle\u3001maxActive)
#      initial-size: 5
#      min-idle: 5
#      max-active: 20
#      # \u914D\u7F6E\u83B7\u53D6\u8FDE\u63A5\u7B49\u5F85\u8D85\u65F6\u7684\u65F6\u95F4
#      max-wait: 10000
#      # \u914D\u7F6E\u95F4\u9694\u591A\u4E45\u624D\u8FDB\u884C\u4E00\u6B21\u68C0\u6D4B\uFF0C\u68C0\u6D4B\u9700\u8981\u5173\u95ED\u7684\u7A7A\u95F2\u8FDE\u63A5\uFF0C\u5355\u4F4D\u662F\u6BEB\u79D2
#      time-between-eviction-runs-millis:  600000
#      # \u914D\u7F6E\u4E00\u4E2A\u8FDE\u63A5\u5728\u6C60\u4E2D\u6700\u5C0F\u751F\u5B58\u7684\u65F6\u95F4\uFF0C\u5355\u4F4D\u662F\u6BEB\u79D2
#      min-evictable-idle-time-millis: 300000
#      validation-query: SELECT 1 FROM DUAL
#      test-while-idle: true
#      test-on-borrow: false
#      test-on-return: false
#      # \u6253\u5F00PSCache\uFF0C\u5E76\u4E14\u6307\u5B9A\u6BCF\u4E2A\u8FDE\u63A5\u4E0APSCache\u7684\u5927\u5C0F
#      pool-prepared-statements: false
#      max-pool-prepared-statement-per-connection-size: 20
#      # \u914D\u7F6E\u76D1\u63A7\u7EDF\u8BA1\u62E6\u622A\u7684filters\uFF0C\u53BB\u6389\u540E\u76D1\u63A7\u754C\u9762sql\u65E0\u6CD5\u7EDF\u8BA1\uFF0C'wall'\u7528\u4E8E\u9632\u706B\u5899
#      filters: stat,wall,slf4j
#      # \u901A\u8FC7connectProperties\u5C5E\u6027\u6765\u6253\u5F00mergeSql\u529F\u80FD\uFF1B\u6162SQL\u8BB0\u5F55
#      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#      #useGlobalDataSourceStat: true # \u5408\u5E76\u591A\u4E2ADruidDataSource\u7684\u76D1\u63A7\u6570\u636E
#      # \u7528\u4E86shardingjdbc\u540E\uFF0C\u4E0A\u9762\u7684\u4E0D\u518D\u751F\u6548\uFF0C\u4E5F\u5BB9\u6613\u7406\u89E3\uFF0C\u56E0\u4E3A\u4ED6\u4E0D\u77E5\u9053\u4F60\u6709\u51E0\u4E2A\u6570\u636E\u6E90\uFF0C\u800C\u4E0B\u9762\u7684\u914D\u7F6E\u548C\u6570\u636E\u6E90\u65E0\u5173
#      web-stat-filter:
#        enabled: true
#        url-pattern: "/*"
#        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
#      # \u914D\u7F6EDruidStatViewServlet
#      stat-view-servlet:
#        enabled: true
#        url-pattern: "/druid/*"
#        # IP\u767D\u540D\u5355(\u6CA1\u6709\u914D\u7F6E\u6216\u8005\u4E3A\u7A7A\uFF0C\u5219\u5141\u8BB8\u6240\u6709\u8BBF\u95EE)
#        allow:
#        # IP\u9ED1\u540D\u5355 (\u5B58\u5728\u5171\u540C\u65F6\uFF0Cdeny\u4F18\u5148\u4E8Eallow)
#        #deny: 192.168.1.100
#        #  \u7981\u7528HTML\u9875\u9762\u4E0A\u7684\u201CReset All\u201D\u529F\u80FD
#        reset-enable: false
#        # \u767B\u5F55\u540D
#        login-username: ENC(xpZqjN8GFIjaOPG7aiuhjQ==)
#        # \u767B\u5F55\u5BC6\u7801
#        login-password: ENC(otXZFZOnzEcmsK4epgHIlA==)


logging:
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include: '*'

pigeonim:
  user:
    id: 13003926701
    username: liangzhenlin
  # \u8DEF\u7531\u5730\u5740
  route:
    url: http://127.0.0.1:8083/
  # \u68C0\u6D4B\u591A\u5C11\u79D2\u6CA1\u6709\u6536\u5230\u670D\u52A1\u7AEF\u7AEF\u5FC3\u8DF3\u540E\u91CD\u65B0\u767B\u5F55\u83B7\u53D6\u8FDE\u63A5
  heartbeat:
    time: 60
  # \u5BA2\u6237\u7AEF\u8FDE\u63A5\u5931\u8D25\u91CD\u8FDE\u6B21\u6570
  reconnect:
    count: 3
